import type { RawAsset } from '../shared/types';
import { escapeAttr, escapeHtml, type Style } from './format';
import type { IRDocument, IRNode } from './ir';

/** inline: data URIs · files: relative asset paths (zip) · preview: shortened data URIs for display */
export type AssetMode = 'inline' | 'files' | 'preview';

export type Emitted = { markup: string; css: string; full: string };

const RESET = `*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

img {
  display: block;
}

button {
  border: none;
  background: none;
  font: inherit;
  color: inherit;
  text-align: inherit;
  cursor: pointer;
}

a {
  color: inherit;
  text-decoration: none;
}`;

const TOKEN = /__ASSET__(.+?)__/g;
const VOID_TAGS = new Set(['img']);

export function toBase64(bytes: Uint8Array): string {
	let binary = '';
	for (let i = 0; i < bytes.length; i += 0x8000) {
		binary += String.fromCharCode.apply(null, bytes.subarray(i, i + 0x8000) as unknown as number[]);
	}
	return btoa(binary);
}

function assetResolver(assets: Map<string, RawAsset>, mode: AssetMode) {
	const cache = new Map<string, string>();
	return (value: string) =>
		value.replace(TOKEN, (_, id: string) => {
			const asset = assets.get(id);
			if (!asset) return '';
			if (mode === 'files') return `assets/${asset.name}`;
			if (mode === 'preview') {
				const kb = Math.max(1, Math.round(asset.bytes.length / 1024));
				return `data:${asset.mime};base64,…(${asset.name}, ${kb} KB)`;
			}
			let uri = cache.get(id);
			if (!uri) {
				uri = `data:${asset.mime};base64,${toBase64(asset.bytes)}`;
				cache.set(id, uri);
			}
			return uri;
		});
}

function rule(selector: string, style: Style, resolve: (v: string) => string): string {
	const lines = Object.entries(style).map(([k, v]) => `  ${k}: ${resolve(v)};`);
	return lines.length ? `${selector} {\n${lines.join('\n')}\n}` : '';
}

const indent = (text: string, spaces: number) =>
	text
		.split('\n')
		.map((line) => (line ? ' '.repeat(spaces) + line : line))
		.join('\n');

function renderRuns(node: IRNode): string {
	const inner = (node.runs ?? [])
		.map((run) => {
			const text = escapeHtml(run.text).replace(/\r\n|\n|\u2028|\u2029/g, '<br>');
			const cls = run.className ? ` class="${run.className}"` : '';
			if (run.href) return `<a href="${escapeAttr(run.href)}"${cls}>${text}</a>`;
			return cls ? `<span${cls}>${text}</span>` : text;
		})
		.join('');
	return node.wrapRuns ? `<span>${inner}</span>` : inner;
}

function renderNode(node: IRNode, depth: number, resolve: (v: string) => string): string {
	const pad = '  '.repeat(depth);
	const attrs = [`class="${node.className}"`];
	for (const [k, v] of Object.entries(node.attrs)) attrs.push(`${k}="${escapeAttr(resolve(v))}"`);
	const open = `<${node.tag} ${attrs.join(' ')}>`;
	if (VOID_TAGS.has(node.tag)) return pad + open;
	if (node.runs) return `${pad}${open}${renderRuns(node)}</${node.tag}>`;
	if (node.children.length === 0) return `${pad}${open}</${node.tag}>`;
	return [pad + open, ...node.children.map((c) => renderNode(c, depth + 1, resolve)), `${pad}</${node.tag}>`].join('\n');
}

export function emit(doc: IRDocument, assets: Map<string, RawAsset>, mode: AssetMode): Emitted {
	const resolve = assetResolver(assets, mode);
	const rules: string[] = [];
	const runClasses = new Set<string>();
	const walk = (node: IRNode) => {
		const r = rule(`.${node.className}`, node.style, resolve);
		if (r) rules.push(r);
		for (const run of node.runs ?? []) {
			if (!run.className || runClasses.has(run.className)) continue;
			runClasses.add(run.className);
			const rr = rule(`.${run.className}`, run.style, resolve);
			if (rr) rules.push(rr);
		}
		node.children.forEach(walk);
	};
	doc.roots.forEach(walk);

	const header = ['/* Generated by SNN Design to HTML/CSS */'];
	if (doc.fonts.length) {
		const list = doc.fonts.map((f) => `${f.family} ${f.weights.join('/')}`).join(', ');
		header.push(`/* Fonts used (not embedded): ${list} */`);
	}
	const variables = doc.variables.length
		? `:root {\n${doc.variables.map((v) => `  ${v.name}: ${v.value};`).join('\n')}\n}`
		: '';
	const css = [header.join('\n'), RESET, variables, ...rules].filter(Boolean).join('\n\n') + '\n';

	const markup = doc.roots.map((n) => renderNode(n, 0, resolve)).join('\n');
	const head =
		mode === 'files' ? '  <link rel="stylesheet" href="styles.css">' : `  <style>\n${indent(css.trimEnd(), 4)}\n  </style>`;
	const full = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(doc.title)}</title>
${head}
</head>
<body>
${indent(markup, 2)}
</body>
</html>
`;
	return { markup: markup + '\n', css, full };
}
