import type { RawEffect, RawPaint, RGBA, TokensResult, TokenValue } from '../shared/types';
import { cssColor, cssSlug, num, px, type StyleCtx, type Units } from './format';
import { gradientCss } from './paint';
import { fontFamilyCss } from './text';

const UNITLESS = /(opacity|weight|z-?index|ratio|scale|line-?height|columns|count|order|flex)/i;

const isAlias = (v: TokenValue): v is { alias: string } => typeof v === 'object' && v !== null && 'alias' in v;
const isColor = (v: TokenValue): v is RGBA => typeof v === 'object' && v !== null && 'r' in v;

type Opts = { units: Units; decimals: number };

function ctxFor(opts: Opts): StyleCtx {
	return {
		px: (n) => px(n, opts.decimals, opts.units),
		len: (n) => px(n, opts.decimals, opts.units),
		color: (c) => cssColor(c),
		asset: () => '',
		warn: () => {},
	};
}

function paintValue(paints: RawPaint[], ctx: StyleCtx): string | null {
	const top = [...paints].reverse().find((p) => p.type === 'SOLID' || p.type.startsWith('GRADIENT'));
	if (!top) return null;
	if (top.type === 'SOLID') return cssColor(top.color);
	if ('transform' in top) return gradientCss(top, 100, 100, ctx);
	return null;
}

function shadowValue(effects: RawEffect[], ctx: StyleCtx): string | null {
	const list = effects
		.filter((e): e is Extract<RawEffect, { color: RGBA }> => e.type === 'DROP_SHADOW' || e.type === 'INNER_SHADOW')
		.reverse()
		.map((e) => `${e.type === 'INNER_SHADOW' ? 'inset ' : ''}${ctx.px(e.x)} ${ctx.px(e.y)} ${ctx.px(e.radius)} ${ctx.px(e.spread)} ${cssColor(e.color)}`);
	return list.length ? list.join(', ') : null;
}

/** Variables (every mode), paint, effect and text styles as a CSS file. */
export function tokensToCss(t: TokensResult, opts: Opts): string {
	const ctx = ctxFor(opts);
	const names = new Map<string, string>();
	const used = new Set<string>();
	for (const col of t.collections) {
		for (const v of col.variables) {
			let name = `--${cssSlug(v.name)}`;
			if (used.has(name)) name = `--${cssSlug(col.name)}-${cssSlug(v.name)}`;
			used.add(name);
			names.set(v.id, name);
		}
	}
	const value = (name: string, type: string, v: TokenValue): string => {
		if (isAlias(v)) return names.has(v.alias) ? `var(${names.get(v.alias)})` : 'initial';
		if (isColor(v)) return cssColor(v);
		if (typeof v === 'number') return type === 'FLOAT' && !UNITLESS.test(name) ? ctx.px(v) : num(v, 4);
		if (typeof v === 'string') return JSON.stringify(v);
		return String(v);
	};

	const blocks: string[] = ['/* Design tokens — generated by SNN Design to HTML/CSS */'];
	for (const col of t.collections) {
		col.modes.forEach((mode, i) => {
			const lines = col.variables.map((v) => `  ${names.get(v.id)}: ${value(v.name, v.type, v.values[mode.id])};`);
			if (!lines.length) return;
			const selector = i === 0 ? ':root' : `[data-${cssSlug(col.name, 'theme')}="${cssSlug(mode.name, 'mode')}"]`;
			blocks.push(`/* ${col.name} — ${mode.name} */\n${selector} {\n${lines.join('\n')}\n}`);
		});
	}

	const styleVars: string[] = [];
	for (const s of t.paintStyles) {
		const v = paintValue(s.paints, ctx);
		if (v) styleVars.push(`  --color-${cssSlug(s.name)}: ${v};`);
	}
	for (const s of t.effectStyles) {
		const v = shadowValue(s.effects, ctx);
		if (v) styleVars.push(`  --shadow-${cssSlug(s.name)}: ${v};`);
	}
	if (styleVars.length) blocks.push(`/* Styles */\n:root {\n${styleVars.join('\n')}\n}`);

	for (const s of t.textStyles) {
		const lines = [
			`  font-family: ${fontFamilyCss(s.fontFamily)};`,
			`  font-size: ${ctx.px(s.fontSize)};`,
			`  font-weight: ${s.fontWeight};`,
		];
		if (s.italic) lines.push('  font-style: italic;');
		if (s.lineHeight.unit === 'PIXELS') lines.push(`  line-height: ${ctx.px(s.lineHeight.value)};`);
		else if (s.lineHeight.unit === 'PERCENT') lines.push(`  line-height: ${num(s.lineHeight.value / 100, 3)};`);
		const spacing = s.letterSpacing.unit === 'PERCENT' ? (s.letterSpacing.value / 100) * s.fontSize : s.letterSpacing.value;
		if (Math.abs(spacing) >= 0.005) lines.push(`  letter-spacing: ${ctx.px(spacing)};`);
		const transform = { UPPER: 'uppercase', LOWER: 'lowercase', TITLE: 'capitalize' }[s.textCase];
		if (transform) lines.push(`  text-transform: ${transform};`);
		if (s.decoration === 'UNDERLINE') lines.push('  text-decoration: underline;');
		blocks.push(`.text-${cssSlug(s.name)} {\n${lines.join('\n')}\n}`);
	}
	return blocks.join('\n\n') + '\n';
}

type Tree = { [key: string]: Tree | unknown };

function setPath(tree: Tree, path: string[], leaf: unknown) {
	let node = tree;
	for (const part of path.slice(0, -1)) {
		const next = node[part];
		if (!next || typeof next !== 'object' || '$value' in (next as Tree)) node[part] = {};
		node = node[part] as Tree;
	}
	node[path[path.length - 1]] = leaf;
}

const pathOf = (name: string) => name.split('/').map((p) => p.trim()).filter(Boolean);

/** W3C Design Tokens Community Group format; extra modes live under $extensions. */
export function tokensToJson(t: TokensResult): string {
	const tree: Tree = {};
	const refs = new Map<string, string>();
	for (const col of t.collections) for (const v of col.variables) refs.set(v.id, `{${[col.name, ...pathOf(v.name)].join('.')}}`);

	const value = (type: string, v: TokenValue): unknown => {
		if (isAlias(v)) return refs.get(v.alias) ?? null;
		if (isColor(v)) return cssColor(v);
		if (typeof v === 'number' && type === 'FLOAT') return v;
		return v;
	};
	const TYPE = { COLOR: 'color', FLOAT: 'number', STRING: 'string', BOOLEAN: 'boolean' } as const;

	for (const col of t.collections) {
		for (const v of col.variables) {
			const [first, ...rest] = col.modes;
			const leaf: Record<string, unknown> = { $type: TYPE[v.type], $value: value(v.type, v.values[first.id]) };
			if (rest.length)
				leaf.$extensions = { modes: Object.fromEntries(col.modes.map((m) => [m.name, value(v.type, v.values[m.id])])) };
			setPath(tree, [col.name, ...pathOf(v.name)], leaf);
		}
	}
	const ctx = ctxFor({ units: 'px', decimals: 2 });
	for (const s of t.paintStyles) {
		const v = paintValue(s.paints, ctx);
		if (v) setPath(tree, ['styles', 'color', ...pathOf(s.name)], { $type: v.startsWith('#') || v.startsWith('rgba') ? 'color' : 'gradient', $value: v });
	}
	for (const s of t.effectStyles) {
		const v = shadowValue(s.effects, ctx);
		if (v) setPath(tree, ['styles', 'shadow', ...pathOf(s.name)], { $type: 'shadow', $value: v });
	}
	for (const s of t.textStyles) {
		setPath(tree, ['styles', 'typography', ...pathOf(s.name)], {
			$type: 'typography',
			$value: {
				fontFamily: s.fontFamily,
				fontWeight: s.fontWeight,
				fontSize: `${num(s.fontSize, 2)}px`,
				lineHeight: s.lineHeight.unit === 'PIXELS' ? `${num(s.lineHeight.value, 2)}px` : s.lineHeight.unit === 'PERCENT' ? num(s.lineHeight.value / 100, 3) : 'normal',
				letterSpacing:
					s.letterSpacing.unit === 'PERCENT' ? `${num(s.letterSpacing.value / 100, 3)}em` : `${num(s.letterSpacing.value, 2)}px`,
			},
		});
	}
	return JSON.stringify(tree, null, 2) + '\n';
}
