const MESSAGES: Record<string, string> = {
	UNSUPPORTED_NODE: 'Layer type has no HTML equivalent — exported as a PNG image.',
	MASK_RASTERIZED: 'Contains a mask — this group was exported as a PNG image.',
	MASK_SKIPPED: 'Mask layer skipped.',
	EXPORT_FAILED: 'Figma could not export this layer as an image.',
	GRADIENT_APPROXIMATE: 'Gradient shape approximated in CSS.',
	IMAGE_CROP_APPROXIMATE: 'Image crop approximated with object-fit / background-size: cover.',
	IMAGE_TILE_APPROXIMATE: 'Tiled image scale is approximate.',
	IMAGE_FILTERS_IGNORED: 'Image adjustments (exposure, contrast, …) are not applied.',
	IMAGE_OPACITY_IGNORED: 'Image fill opacity cannot be applied to a CSS background.',
	IMAGE_MISSING: 'Image data could not be read.',
	PAINT_BLEND_IGNORED: 'Fill blend mode ignored.',
	PAINT_UNSUPPORTED: 'Fill type not supported in CSS (video, pattern or shader).',
	MULTIPLE_FILLS_SIMPLIFIED: 'Multiple fills simplified.',
	TEXT_IMAGE_FILL_UNSUPPORTED: 'Image fill on text is not supported.',
	MULTIPLE_STROKES_SIMPLIFIED: 'Multiple strokes simplified to the top one.',
	STROKE_PAINT_UNSUPPORTED: 'Stroke paint type not supported.',
	GRADIENT_STROKE_SIMPLIFIED: 'Gradient stroke replaced by its first color.',
	DASH_PATTERN_APPROXIMATE: 'Dash pattern approximated with a dashed line.',
	TEXT_STROKE_APPROXIMATE: 'CSS text strokes are always centered.',
	STROKE_ALIGN_APPROXIMATE: 'Per-side stroke drawn inside the box.',
	TEXT_INNER_SHADOW_UNSUPPORTED: 'Inner shadow on text is not supported.',
	TEXT_SHADOW_SPREAD_IGNORED: 'CSS text shadows have no spread.',
	PROGRESSIVE_BLUR_APPROXIMATE: 'Progressive blur replaced with a uniform blur.',
	BLUR_APPROXIMATE: 'Blur converted as Figma radius ÷ 2 — check visually.',
	EFFECT_UNSUPPORTED: 'Effect not supported in CSS.',
	ROTATION_APPROXIMATE: 'Rotated layer inside Auto Layout — spacing may differ.',
	NEGATIVE_SPACING: 'Negative Auto Layout spacing is not supported by CSS gap.',
	REVERSE_Z_IGNORED: '"Last on top" stacking order ignored.',
	BLEND_MODE_UNSUPPORTED: 'Layer blend mode has no CSS equivalent.',
	PLACEHOLDER_HREF: 'Link layer exported with a placeholder href="#".',
	TEXT_LIST_SIMPLIFIED: 'Bulleted/numbered list exported as plain text.',
	PARAGRAPH_SPACING_IGNORED: 'Paragraph spacing ignored (lines joined with <br>).',
	VARIABLE_MODE_CONFLICT: 'Variable resolves to a different value here — literal value used.',
	CUSTOM_FONT_NOT_EMBEDDED: 'Commercial or system font, not on Google Fonts — self-host it with @font-face.',
	FORM_CONTROL_SIMPLIFIED: 'Form control built from its first text layer — icons and extra layers inside were dropped.',
	LINK_TARGET_OUTSIDE: 'Prototype link points to a frame outside the export — href="#" used.',
	BREAKPOINT_CONTENT_DIFFERS: 'Text differs between breakpoint frames — the text of the largest frame is used.',
	CHECK_NO_AUTO_LAYOUT: 'No Auto Layout — children are positioned absolutely. Add Auto Layout (Shift + A) for flexible code.',
	CHECK_INFERRED_LAYOUT: 'No Auto Layout — rows and columns were guessed. Add Auto Layout to be sure.',
	CHECK_GROUP: 'Group instead of frame — groups cannot use Auto Layout, so children are positioned absolutely.',
	CHECK_ABSOLUTE_CHILDREN: 'Several children use "Ignore Auto Layout" (absolute position).',
	CHECK_GENERIC_NAME: 'Default layer name — rename it so classes and tags are meaningful (e.g. "Header", "Card").',
	CHECK_IMAGE_ALT: 'Image has a default layer name, so its alt text is empty. Name the layer to describe the image.',
	CHECK_HEADING_SKIP: 'Heading level skipped — screen readers expect h1 → h2 → h3.',
	CHECK_MULTIPLE_H1: 'More than one h1 on the page.',
};

export function describeWarning(code: string): string {
	return MESSAGES[code] ?? code;
}
